### ISSUE TITLE
Extra transitions highlighted

### ISSUE THREAD

**Issue by dehall** [synthetichealth/caremaps-react#27]
The highlighting when a state is selected that indicates the "previous" states can include too many transitions. Seems like it's including a range of transitions when it should include a single one

Example module - Examplitis: Examplitol can transition to Pre_Examplotomy, Last_Days, or Terminal
![module_1](https://user-images.githubusercontent.com/13512036/35169625-31aedc72-fd2b-11e7-86e9-fb741b912855.PNG)

Selecting Terminal - looks good
![module_2](https://user-images.githubusercontent.com/13512036/35169639-3d640556-fd2b-11e7-89aa-355854e35886.PNG)

Selecting Last_Days - the arrow towards Terminal is black but should be grayed out
![module_3](https://user-images.githubusercontent.com/13512036/35169766-cab787c0-fd2b-11e7-8195-1e3f1925fcca.PNG)

Selecting Pre_Examplotomy - the arrows toward Terminal and Last_Days are black but should be grayed out
![module_4](https://user-images.githubusercontent.com/13512036/35169768-cd0d103a-fd2b-11e7-9947-37dbbbb6f553.PNG)

**Comment by arscan** [comment]
This was originally a bug, but then I started thinking of it as a feature because in some cases it is helpful to see all transition information from the previous state so you can understand the transition into the selected state.  Mainly this is useful for the if/else type transitions... just seeing the transition into your state labeled 'else' with no other information is not very helpful.  What do you think?  I'm leaning towards this being a bug, because even if it is helpful to have more information, it isn't immediately evident why that information is shown.

Having said that, the "last days" one is definitely wrong because at the very least this needs to be consistent.  Showing 2 of the 3 transitions from the previous state makes no sense.
